version: '3'
services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - USER_NAME=${USER_NAME}
        - USER_PASSWORD=${USER_PASSWORD}
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '${CPU_LIMIT}'
          memory: '${RAM_LIMIT}'
    ports:
      - 22:22
      - 8888:8888